apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-pg-certmanager
spec:
  # Secret names are always required.
  secretName: prod-pg-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - prod-pg-org
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: prod-pg-primary
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - key encipherment
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  - prod-pg-primary
  - prod-pg-primary.postgres-operator
  - prod-pg-primary.postgres-operator.svc
  - prod-pg-primary.postgres-operator.svc.cluster.local
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
