---
- name: Deploy rke servers
  hosts: rke2_lb
  become: true
  become_method: sudo
  tasks:
    - name: Common role
      ansible.builtin.include_tasks: 00_common.yml

    - name: Install nginx
      ansible.builtin.dnf:
        name:
          - nginx

    - name: Create registry and repo nginx config
      ansible.builtin.template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"
        mode: 0644
        owner: root
        group: root

    - name: Set SELinux context
      ansible.builtin.command:
        semanage permissive -a httpd_t

    - name: Open firewall port for http/https/ssh
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      with_items:
        - 80/tcp
        - 443/tcp
        - 6443/tcp
        - 9345/tcp

    - name: Reload haproxy service
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: true
