---
- name: Create postgres namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ playbook_dir }}/files/rke2.yaml"
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: postgres-operator
    state: present

- name: Deploy postgres operator
  ansible.builtin.command:
    "kubectl apply --server-side  -k {{ playbook_dir }}/../services/postgres/install/default/ --kubeconfig {{ playbook_dir }}/files/rke2.yaml"

- name: Deploy postgres cluster
  ansible.builtin.command:
    "kubectl apply -k {{ playbook_dir }}/../services/postgres/ --kubeconfig {{ playbook_dir }}/files/rke2.yaml"
