---
- name: Configure k8s
  hosts: localhost
  tasks:
    - name: Set domain var
      ansible.builtin.set_fact:
        domain: ".{{ workspace }}"

    - name: Certificate role
      include_tasks: 10_certificate.yml

    - name: Rook role
      include_tasks: 11_rook.yml

    - name: Postgres role
      include_tasks: 12_postgres.yml

    - name: Metallb role
      include_tasks: 13_metallb.yml

    - name: Keycloak role
      include_tasks: 14_keycloak.yml

    - name: Portal role
      include_tasks: 15_portal.yml
